import { spawn } from 'child_process';
import http from 'http';
import fs from 'fs';
const CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const port=9521;
const url="file://"+process.cwd()+"/index.html";
const chrome=spawn(CHROME,["--headless=new",`--remote-debugging-port=${port}`,"--disable-gpu","--hide-scrollbars","--window-size=390,844",url],{stdio:"ignore"});
const get=(p)=>new Promise((res)=>{const r=()=>http.get(`http://127.0.0.1:${port}${p}`,x=>{let d="";x.on("data",c=>d+=c);x.on("end",()=>res(JSON.parse(d)))}).on("error",()=>setTimeout(r,200));r()});
await new Promise(r=>setTimeout(r,1500));
const tabs=await get("/json");
const ws=new WebSocket(tabs.find(t=>t.type==="page").webSocketDebuggerUrl);
let id=0; const pending=new Map();
const send=(m,p={})=>new Promise(res=>{const i=++id;pending.set(i,res);ws.send(JSON.stringify({id:i,method:m,params:p}))});
await new Promise(r=>ws.addEventListener("open",r));
ws.addEventListener("message",e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id);}});
await send("Runtime.enable");await send("Page.enable");
await send("Emulation.setDeviceMetricsOverride",{width:390,height:844,deviceScaleFactor:2,mobile:true});
await new Promise(r=>setTimeout(r,500));
const s=await send("Page.captureScreenshot",{format:"png",clip:{x:0,y:0,width:390,height:120,scale:2}});fs.writeFileSync("_main_hdr.png",Buffer.from(s.result.data,"base64"));
chrome.kill();process.exit(0);
